language: python
python:
  - "3.5"
env:
  -DJANGO=2.0
install:
  - pip install -r requirements.txt

script:
  - python manage.py test
  - coverage run --source="." manage.py test
  
after_success:
  coveralls
